config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email.downcase! }
  validates :username,
                presence: true,
                uniqueness: { case_sensitive: false},
                length: {min: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
                presence: true,
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    respond_to do |format|
      if @article.save
        flash[:success] = "Article was successfully created"
        format.html { redirect_to article_path(@article) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def edit
  end

  def update
    @article.user = User.first
    respond_to do |format|
      if @article.update(article_params)
        flash[:success] = "Article was successfully updated"
        format.html { redirect_to article_path(@article) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def show
  end

  def destroy
    @article.destroy

    flash[:danger] = "Article was successfully deleted"
    redirect_to article_path, status: :see_other
  end

  private
    def set_article
      # here :id means path variable
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController # extends ApplicationController

  def home
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    debugger
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = "User was successfully created"
        format.html { redirect_to articles_path }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "User was successfully updated"
        format.html { redirect_to articles_path }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded")
  end
end

app/views/articles/_article.erb
 <% obj.each do |article| %>
        <div class="row">
            <div class="col-sm-8 offset-sm-2">
                <div class="well well-lg">
                    <div class="article-title">
                        <%= link_to article.title, article_path(article) %>
                    </div>
                    <div class="article-body">
                        <%= truncate(article.description, length: 100) %>
                        <div class="article-meta-details">
                            <small>Created by:
                                <%= link_to article.user.username, user_path(article.user) if article.user%>,
                                <%= time_ago_in_words(article.created_at) %> ago,
                                last updated: <%= time_ago_in_words(article.updated_at) %> ago
                            </small>
                        </div>
                    </div>
                    <div class="article-actions">
                        <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-primary" %>
                        <%= link_to 'Delete this article',
                            article_path(article),
                            data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure you want to delete the artcle?"
                            },
                            class: "btn btn-danger"
                        %>
                        <%= link_to 'Back to article listing', articles_path, class: "btn btn-success" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row mt-1">
    <%= form_for @article do |f| %>
        <div class="mb-4 row">
            <div class="col-sm-2">
                <%= f.label :title, class: "col-form-label" %>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true%>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="col-sm-2">
                <%= f.label :description, class: "col-form-label" %>
            </div>
            <div class="col-sm-10">
                <%= f.text_area :description, class: "form-control", placeholder: "Description of title", rows: 10 %>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="offset-sm-2 col-sm-10">
                <%= f.submit class: "btn btn-primary btn-lg" %>
            </div>
        </div>

    <% end %>
    <div class="col-sm-4 offset-sm-4">
        [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>


   <%= render 'article', obj: @articles %>
</table>

app/views/articles/new.html.erb
<h1 align="center">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-sm-8 offset-sm-2">
    <div class="center">
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 offset-md-4">
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                </div>
            </div>
        </ul>
    </div>

    <h4 class="center"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-primary" %>
        <%= link_to 'Delete this article',
            article_path(@article),
            data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to delete the artcle?"
            },
            class: "btn btn-danger"
        %>
        <%= link_to 'Back to article listing', articles_path, class: "btn btn-success" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://www.nyyu.io">The complete Ruby on Rails Developer</a>
            by <a href="https://www.Ximing.com">Ximing Gao</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row mt-2">
    <div class="col-sm-10 offset-sm-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %> alert-dismissible' role="alert">
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Action
          </a>
          <ul class="dropdown-menu">
            <li>
                <%= link_to "New article", new_article_path, class: "dropdown-item" %>
            </li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/layouts/navigation' %>
    <%= render '/layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render '/layouts/footer' %>
    <br>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron p-5 my-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">ALPHA BLOG</h1>
        <p class="col-md-8 fs-4"></p>
        <%= link_to 'Sign up now', '#', class: "btn btn-primary btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row mb-4">
        <div class="col-sm-10 offset-sm-2">
            <div class="bg-danger bg-opacity-25 rounded-3 p-3">
                <h5 class="text-danger">
                    <%= pluralize(obj.errors.count, "error") %>
                    prohibited this article from being saved:
                </h5>
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li class="text-danger"><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row mt-1">
    <%= form_for @user do |f| %>
        <div class="mb-4 row">
            <div class="col-sm-2">
                <%= f.label :username, class: "col-form-label" %>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true%>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="col-sm-2">
                <%= f.label :email, class: "col-form-label" %>
            </div>
            <div class="col-sm-10">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="col-sm-2">
                <%= f.label :password, class: "col-form-label" %>
            </div>
            <div class="col-sm-10">
                <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="offset-sm-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary btn-lg") %>
            </div>
        </div>

    <% end %>
    <div class="col-sm-4 offset-sm-4">
        [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
</div>

app/views/users/_user.html.erb
<div align="center">
    <% users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 offset-md-4">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                </div>
            </div>
        </ul>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">List Users</h1>

<%= render 'user', users: @users%>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to, <%= @user.username %>'s page</h1>

<div class="row">
    <div class="col-md-4 offset-md-4 center">
        <%= gravatar_for @user, size: 150%>
    </div>
</div>

<h4 align="center"><%= @user.username %>'s articles </h4>
<%= render 'articles/article', obj: @user.articles %>